# Generated by Django 4.2.13 on 2024-05-10 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('govt_id_type', models.CharField(choices=[('AADHAR', 'Aadhar'), ('VOTER_ID', 'Voter Id'), ('PAN', 'PAN'), ('PASSPORT', 'Passport')], max_length=20)),
                ('govt_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('JOINT', 'Joint'), ('INDIVIDUAL', 'Individual')], max_length=20)),
                ('category', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential')], max_length=20)),
                ('load_applied_value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('date_of_application', models.DateField()),
                ('modified_date', models.DateField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CONNECTION_RELEASED', 'Connection Released'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reviewer_comments', models.CharField(blank=True, choices=[('INSTALLATION_PENDING', 'Installation Pending'), ('DOCUMENTS_VERIFICATION_IN_PROGRESS', 'Documents Verification In Progress'), ('INSTALLATION_COMPLETED', 'Installation Completed'), ('KYC_FAILED', 'KYC Failed')], max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_submitted', to='electricity_board.applicant')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_reviewed', to='electricity_board.reviewer')),
            ],
        ),
    ]
